# Change these first
owner: bdrops-GmbH # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: CB App API
    url: https://app.cbmode.de/app/tiles
  - name: CB Mode
    url: https://cbmode.de
  - name: CB Shop
    url: https://shop.cbmode.de
  - name: Zingst
    url: https://www.zingst.de
  - name: CASE
    url: https://cloppenburg-gruppe.de
  - name: bdrops.de
    url: https://bdrops.de

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.bdrops.space
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://bdrops.de/sites/all/themes/responsivebase/images/logo2x.png
  name: bdrops Upptime
  introTitle: "**Upptime** ist ein Open Source Uptime Monitor, powered by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Translation
i18n:
  activeIncidents: Aktive Störungen
  activeScheduledMaintenance: Aktive geplante Wartungsarbeiten
  allSystemsOperational: Alle Systeme sind betriebsbereit
  incidentReport: "Ticket zu Störung #$NUMBER →"
  activeIncidentSummary: Eröffnet am $DATE mit $POSTS Kommentaren
  incidentTitle: Details zu Störung $NUMBER
  incidentDetails: Details zur Störung
  incidentFixed: Behoben
  incidentOngoing: Dauert an
  incidentOpenedAt: 'Eröffnet am/um'
  incidentClosedAt: 'Geschlossen am/um'
  incidentSubscribe: Updates abonnieren
  incidentViewOnGitHub: Auf GitHub ansehen
  incidentCommentSummary: Geposted am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Störungen
  pastIncidents: Vergangene Störungen
  pastIncidentsResolved: Behoben in $MINUTES Minuten mit $POSTS Kommentaren
  pastScheduledMaintenance: Frühere geplante Wartungsarbeiten
  liveStatus: Live Status
  overallUptime: "Gesamtbetriebszeit: $UPTIME"
  overallUptimeTitle: Uptime gesamt
  averageResponseTime: "Durchschnittliche Reaktionszeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Reaktionszeit
  sevelDayResponseTime: 7-Tage Reaktionszeit
  responseTimeMs: Reaktionszeit (ms)
  up: Up
  down: Down
  degraded: Schlechte Reaktionszeit
  ms: ms
  loading: Lade
  complete: Abgeschlossen
  navGitHub: GitHub
  footer: Diese Seite ist [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Token kopieren und einfügen
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: Beim Abrufen der Statusdetails ist ein Fehler aufgetreten.
  errorText: Sie können es gleich noch einmal probieren.
  errorHome: Gehe zur Startseite
